import type { Metadata } from "next";
import { Cairo, Rubik } from "next/font/google";
import "./globals.css";
const cairo = Cairo({ subsets: ["arabic"], display: "swap", weight: "400"  });
const rubik = Rubik({ subsets: ["latin"], display: "swap", weight: "400"  });
export const metadata: Metadata = {
  title: "Careio",
  description: "Generated by hakeem",
};


export default function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: { lang: string };
}>) {
  return (
    <html
      lang={params.lang}
      className={params.lang === "ar" ? cairo.className : rubik.className}
    >
      <body className=" bg-[#ECFAFF]">{children}</body>
    </html>
  );
}
