import type { Metadata } from "next";
import { Inter, Cairo, Rubik } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const cairo = Cairo({ subsets: ["latin"] });

const rubik = Rubik({ subsets: ["latin"] });
const lang: string = "en";

export const metadata: Metadata = {
  title: "Careio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={lang == "ar" ? cairo.className : rubik.className}>
        {children}
      </body>
    </html>
  );
}
